buildVariable: true
buildStatic: true
sources:
  - Linefont.designspace
familyName: Linefont
# note - gftools has own order of axes in produced file
axisOrder:
  - wdth
  - wght
stat:
  - name: Width
    tag: wdth
    values:
    - name: Default
      value: 100
      flags: 2
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100