buildVariable: true
buildStatic: true
sources:
  - Linefont.designspace
familyName: Linefont
# note - gftools has own order of axes in produced file
axisOrder:
  - wdth
  - wght
stat:
  - name: Width
    tag: wdth
    values:
    - name: Default
      value: 10
      flags: 2
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      flags: 2
