buildVariable: true
buildStatic: true
sources:
  - Linefont.designspace
familyName: Linefont
axisOrder:
  - wdth
  - wght
# needs to custom the STAT for Hairline and ExtraBlack which won't be generated automatically.
