buildVariable: true
buildStatic: true
sources:
  - Linefont.designspace
familyName: Linefont
# note - gftools has own order of axes in produced file
axisOrder:
  - wdth
  - wght
stat:
  - name: Width
    tag: wdth
    values:
    - name: Default
      value: 100
      flags: 2
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: Black
      value: 900
      flags: 2
